name: Code Preview
on: [push]
jobs:
  push_to_registry:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Login to Container Registry
        env:
          REGISTRY_USER:  ${{ secrets.GHCR_USER }}
          REGISTRY_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
        run: docker login ghcr.io -u $REGISTRY_USER -p $REGISTRY_PASSWORD
      - name: Build and Publish Images
        env:
          IMAGE_BACKEND_NAME: ghcr.io/0va/ipfs-pinning-backend
          IMAGE_CLUSTER_CLIENT_NAME: ghcr.io/0va/ipfs-pinning-cluster-client
        run: IMAGE_VERSION=commit-${GITHUB_SHA:0:7} make build-images && IMAGE_VERSION=commit-${GITHUB_SHA:0:7} make push-images
